In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

# Load the saved features and labels
all_features_vgg16 = np.load('/Users/saikarthik/Desktop/scp/ga_vgg16/all_features_vgg16.npy')
all_labels_vgg16 = np.load('/Users/saikarthik/Desktop/scp/ga_vgg16/all_labels_vgg16.npy')

# Print shape to verify loading
print(f'Features shape: {all_features_vgg16.shape}')
print(f'Labels shape: {all_labels_vgg16.shape}')


Features shape: (6672, 25088)
Labels shape: (6672, 4)


In [2]:
all_features_vgg19 = np.load('/Users/saikarthik/Desktop/scp/ga_vgg19/all_features_vgg19.npy')
all_labels_vgg19 = np.load('/Users/saikarthik/Desktop/scp/ga_vgg19/all_labels_vgg19.npy')

# Print shape to verify loading
print(f'Features shape: {all_features_vgg16.shape}')
print(f'Labels shape: {all_labels_vgg16.shape}')

Features shape: (6672, 25088)
Labels shape: (6672, 4)


In [3]:
from tensorflow.keras.models import load_model

# Load the best VGG16 and VGG19 models
best_vgg16_model = load_model('/Users/saikarthik/Desktop/scp/ga_vgg16/best_vgg16.h5')
best_vgg19_model = load_model('/Users/saikarthik/Desktop/scp/ga_vgg19/best_vgg19.h5')


2024-11-15 19:47:11.727528: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1 Pro
2024-11-15 19:47:11.727562: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2024-11-15 19:47:11.727572: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.33 GB
2024-11-15 19:47:11.727608: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:303] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-11-15 19:47:11.727622: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:269] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [4]:
all_features_vgg16

array([[-0.02366601, -0.02984692, -0.03679322, ..., -0.03021036,
         0.12961806, -0.05106451],
       [-0.02366601, -0.02984692, -0.03679322, ..., -0.03021036,
        -0.12863688, -0.05106451],
       [-0.02366601, -0.02984692, -0.03679322, ..., -0.03021036,
        -0.72598183, -0.05106451],
       ...,
       [-0.02366601, -0.02984692, -0.03679322, ..., -0.03021036,
        -0.44760674, -0.05106451],
       [-0.02366601, -0.02984692, -0.03679322, ..., -0.03021036,
        -0.72598183, -0.05106451],
       [-0.02366601, -0.02984692, -0.03679322, ..., -0.03021036,
        -0.11591294, -0.05106451]], dtype=float32)

In [6]:
all_features_vgg19

array([[-1.2288334e-02, -2.8639566e-02, -4.1679051e-02, ...,
        -1.2243470e-02, -3.4375422e-02,  1.6440372e+01],
       [-1.2288334e-02, -2.8639566e-02, -4.1679051e-02, ...,
        -1.2243470e-02, -3.4375422e-02, -5.7346612e-02],
       [-1.2288334e-02, -2.8639566e-02, -4.1679051e-02, ...,
        -1.2243470e-02, -3.4375422e-02, -5.7346612e-02],
       ...,
       [-1.2288334e-02, -2.8639566e-02, -4.1679051e-02, ...,
        -1.2243470e-02, -3.4375422e-02, -5.7346612e-02],
       [-1.2288334e-02, -2.8639566e-02, -4.1679051e-02, ...,
        -1.2243470e-02, -3.4375422e-02, -5.7346612e-02],
       [-1.2288334e-02, -2.8639566e-02, -4.1679051e-02, ...,
        -1.2243470e-02, -3.4375422e-02, -5.7346612e-02]], dtype=float32)

In [5]:
all_labels_vgg16

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])

In [8]:
all_labels_vgg19

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])