In [286]:
import numpy as np
from sklearn.model_selection import train_test_split

# Load the saved features and labels
all_features_vgg16 = np.load('/Users/saikarthik/Desktop/scp/ga_vgg16/all_features_vgg16.npy')
all_labels_vgg16 = np.load('/Users/saikarthik/Desktop/scp/ga_vgg16/all_labels_vgg16.npy')

# Print shape to verify loading
print(f'Features shape: {all_features_vgg16.shape}')
print(f'Labels shape: {all_labels_vgg16.shape}')


Features shape: (6672, 25088)
Labels shape: (6672, 4)


In [287]:
all_features_vgg19 = np.load('/Users/saikarthik/Desktop/scp/ga_vgg19/all_features_vgg19.npy')
all_labels_vgg19 = np.load('/Users/saikarthik/Desktop/scp/ga_vgg19/all_labels_vgg19.npy')

# Print shape to verify loading
print(f'Features shape: {all_features_vgg16.shape}')
print(f'Labels shape: {all_labels_vgg16.shape}')

Features shape: (6672, 25088)
Labels shape: (6672, 4)


In [288]:
from tensorflow.keras.models import load_model

# Load the best VGG16 and VGG19 models
best_vgg16_model = load_model('/Users/saikarthik/Desktop/scp/ga_vgg16/best_vgg16.h5')
best_vgg19_model = load_model('/Users/saikarthik/Desktop/scp/ga_vgg19/best_vgg19.h5')


OSError: No file or directory found at /Users/saikarthik/Desktop/scp/ga_vgg16/best_vgg16.h5

In [ ]:
all_features_vgg16

array([[-0.02366601, -0.02984692, -0.03679322, ..., -0.03021036,
         0.12961806, -0.05106451],
       [-0.02366601, -0.02984692, -0.03679322, ..., -0.03021036,
        -0.12863688, -0.05106451],
       [-0.02366601, -0.02984692, -0.03679322, ..., -0.03021036,
        -0.72598183, -0.05106451],
       ...,
       [-0.02366601, -0.02984692, -0.03679322, ..., -0.03021036,
        -0.44760674, -0.05106451],
       [-0.02366601, -0.02984692, -0.03679322, ..., -0.03021036,
        -0.72598183, -0.05106451],
       [-0.02366601, -0.02984692, -0.03679322, ..., -0.03021036,
        -0.11591294, -0.05106451]], dtype=float32)

In [ ]:
all_features_vgg19

array([[-1.2288334e-02, -2.8639566e-02, -4.1679051e-02, ...,
        -1.2243470e-02, -3.4375422e-02,  1.6440372e+01],
       [-1.2288334e-02, -2.8639566e-02, -4.1679051e-02, ...,
        -1.2243470e-02, -3.4375422e-02, -5.7346612e-02],
       [-1.2288334e-02, -2.8639566e-02, -4.1679051e-02, ...,
        -1.2243470e-02, -3.4375422e-02, -5.7346612e-02],
       ...,
       [-1.2288334e-02, -2.8639566e-02, -4.1679051e-02, ...,
        -1.2243470e-02, -3.4375422e-02, -5.7346612e-02],
       [-1.2288334e-02, -2.8639566e-02, -4.1679051e-02, ...,
        -1.2243470e-02, -3.4375422e-02, -5.7346612e-02],
       [-1.2288334e-02, -2.8639566e-02, -4.1679051e-02, ...,
        -1.2243470e-02, -3.4375422e-02, -5.7346612e-02]], dtype=float32)

In [ ]:
all_labels_vgg16

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])

In [ ]:
all_labels_vgg19

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])